[package]
name = "temprs"
version = "0.2.5"
authors = ["Jacob Menke <linux.dev25@gmail.com>"]
edition = "2018"
description = "A temporary file manager with stack mechanism"
license = "MIT"
repository = "https://github.com/MenkeTechnologies/temprs"
homepage = "https://github.com/MenkeTechnologies/temprs"

[[bin]]
name = "temprs"
path = "src/main.rs"

[[bin]]
name = "tp"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.13"
log = "0.4"
env_logger = "0.7.1"
simple_logger = "1.3.0"
regex = "1.4.2"
clap = "2.3.3"
